config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  devise_for :users
  namespace :users do
    root to: 'dashboard#index'
    resources :users
  end

  resources :translations
  resources :responses


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/response.rb
class Response < ApplicationRecord

  has_attached_file :sourcefile
  validates_attachment_size :sourcefile, :less_than => 2.megabytes
  validates_attachment_content_type :sourcefile, :content_type => ['text/plain', 'application/pdf', 'application/msword' ]

  belongs_to :user
  belongs_to :translation
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :user
end

app/models/translation.rb
class Translation < ApplicationRecord

  has_attached_file :sourcefile
  validates_attachment_size :sourcefile, :less_than => 2.megabytes
  validates_attachment_content_type :sourcefile, :content_type => ['text/plain', 'application/pdf', 'application/msword' ]

  belongs_to :user
  has_many :responses

  def to_label
    "#{id}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :roles
  has_many :translations
  has_many :responses

  def has_role?(*roles)
     !self.roles.where(identifier: roles).empty?
  end

  def update_with_or_without_pwd(params)
    update_method = :update_without_password
    unless params[:password].blank?
      update_method = :update
    end

    send(update_method, params)
  end

private
  def ensure_that_exist_at_one_user_as_interpreter
    rr = Role.find_by(identifier: :interpreter)

    if !new_record? && rr && rr.user_ids.empty?
      errors.add(:roles,
      "Deve existir ao menos um usuário com o papel de 'Tradutor'")
      return false
    else
      return true
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout :layout_by_resource

  def after_sign_in_path_for(resource)
    return users_root_path if resource.is_a? User
    return customers_root_path if resource.is_a? Customer
  end

  def after_sign_out_path_for(resource)
    return new_user_session_path if resource == :user
    return new_customer_session_path if resource == :customer
  end

  protected
  def layout_by_resource
    return "layouts/session" if devise_controller?

    "layouts/application"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def index
  	@responses = Response.all
    @translations = Translation.all
  end

  def new
      @response = Response.new
  end

  def show
    	@response = Response.find(params[:id])
  end

  def create

    @response = Response.new response_params
    @response.user = current_user

    if @response.save
      flash[:success] = "Resposta cadastrada com sucesso"
      redirect_to :back
    else
      flash.now[:error] = "Existem dados incorretos no formulário"
      redirect_to :back
    end
  end

  def edit
     @response = Response.find(params[:id])
  end

  def update
    @response = Response.find(params[:id])

    if @response.update response_params
      flash[:success] = "Resposta atualizada com sucesso"
    else
      flash[:error] = "Existem dados incorretos no formulário"
      render :edit
    end
  end

  def destroy
    @response = Response.find(params[:id])
    @response.destroy
    flash[:notice] = "Resposta removida com sucesso"
    redirect_to :back
  end

private
  def response_params
    params.require(:response)
    .permit(:message, :sourcefile, :translation_id)
  end

end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController

  def index
  	@translations = Translation.all
  end

  def new
    @translation = Translation.new
  end

  def show
    @translation = Translation.find(params[:id])
    @responses = Response.all
    @response = Response.new
    @response.translation = @translation
  end

  def create
    @translation = Translation.new (translation_params)
    @translation.user = current_user

    if @translation.save
      flash[:success] = "Tradução cadastrada com sucesso"
      redirect_to translations_path
    else
      flash.now[:error] = "Existem dados incorretos no formulário"
      render :new
    end
  end

  def edit
     @translation = Translation.find(params[:id])
  end

  def update
    @translation = Translation.find(params[:id])

    if @translation.update translation_params
      flash[:success] = "Tradução atualizada com sucesso"
    else
      flash[:error] = "Existem dados incorretos no formulário"
      render :edit
    end
  end

  def destroy
    @translation = Translation.find(params[:id])
    @translation.destroy
    flash[:notice] = "Tradução removida com sucesso"
    redirect_to translations_path
  end

private
  def translation_params
    params.require(:translation)
    .permit(:subject, :description, :sourcefile)
  end



end

app/controllers/users/app_user_controller.rb
class Users::AppUserController < ApplicationController
  layout 'users/layouts/application'

  before_action :authenticate_user!
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < Users::AppUserController
  def index
    @users = User.all
    @translations = Translation.all
  end
end

app/controllers/users/users_controller.rb
class Users::UsersController < Users::AppUserController

  def index
    @users = User.all
    @translations = Translation.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end


  def create
    @user = User.new user_params

    if @user.save
      flash[:success] = "Usuário #{@user.name} criado com sucesso"
      redirect_to users_users_path
    else
      flash.now[:error] = "Existem dados incorretos no formulário"
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_with_or_without_pwd user_params
      flash[:success] = "Usuário #{@user.name} atualizado com sucesso"
      redirect_to users_users_path
    else
      flash[:error] = "Existem dados incorretos no formulário"
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "Usuário #{@user.name} removido com sucesso"
    redirect_to users_users_path
  end


  def destroy
    @user = User.find(params[:id])

    if current_user == @user
      flash[:error] = "Você não pode se autoremover"
    else
      @user.destroy
      flash[:notice] = "Usuário #{@user.name} removido com sucesso"
    end

    redirect_to users_users_path
  end

private
  def user_params
    params.require(:user)
    .permit(:name, :email, :password, :password_confirmation, {role_ids: []})
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
      { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning',
        notice: 'alert-info' }[flash_type.to_sym] || flash_type.to_s
  end

  def bootstrap_icon_for(flash_type)
      { success: 'ok-circle', error: 'remove-circle', alert: 'warning-sign',
        notice: 'exclamation-sign' }[flash_type] || 'question-sign'
  end

  def full_title(page_title = '', base_title = 'PHew')
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/customers/dashboard_helper.rb
module Customers::DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/views/home/index.html.erb
<div class="horizontal-centering vertical-centering">
  <%= image_tag 'logos/logo.png', class: 'img-responsive'  %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
      data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(root_path, class: "navbar-brand") do %>
        PHEW! Traduções Colaborativas
      <% end %>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Entrar",  new_user_session_url %></li>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title><%= full_title(yield(:head_title)) %></title>
      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>



      <div id="page-header">
           <%= render 'layouts/navbar'%>
      </div> <!-- page-header -->

          <div class="container">
            <%= yield %>
          </div>
    </body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:head_title)) %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'session', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'session', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div id="<%= controller_name %>-<%= action_name %>" class="container">
    <div class="vertical-centering horizontal-centering">

      <%= render 'devise/shared/flash_messages'%>

      <div>
        <h3 class="text-center gray-text2"><%= yield :title %></h3>
        <p class="gray-text2"><%= yield :sub_title %></p>
      </div>

      <%= yield %>
      
    </div> <!-- .vertical-centering .horizontal-centering -->
  </div> <!-- #home-index -->
</body>
</html>

app/views/responses/_form.html.erb
<%= simple_form_for @response do |f| %>
  <div class="form-inputs">
    <%= f.input :message, autofocus: true %>
    <%= f.input :sourcefile, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>


<% end %>

app/views/responses/edit.html.erb
<%= provide(:title, 'Editar Tradução') %>

<head>
    <title><%= full_title(yield(:head_title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'customers/application',
        media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'customers/application',
        'data-turbolinks-track': 'reload' %>
</head>

<body>



  <div class="center jumbotron"> <h3>Editar Tradução</h3> </dir>
<%= render 'form' %>

app/views/responses/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:head_title)) %></title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'users/application',
            media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'users/application',
            'data-turbolinks-track': 'reload' %>
    </head>

    <body>

      <div id="page-header">
           <%= render 'users/layouts/navbar'%>
      </div> <!-- page-header -->


      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
            <%= render 'users/layouts/sidebar' %>
          </div> <!-- sidebar -->

          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <section id="<%= controller_name %>-<%= action_name %>" >

              <%= render 'devise/shared/flash_messages'%>



              <header class="page-header">
                <h1>Traduções Respondidas</h1>
              </header>


              <table class="table table-hover table-bordered">
                <thead>
                  <tr>
                    <th>Usuário</th>
                    <th>Assunto</th>
                    <th>Descrição</th>
                    <th>Criado em</th>
                    <th>Última atualização</th>
                    <th>Arquivo</th>
                    <th>Opções</th>
                  </tr>
                </thead>
                <tbody>
                  <% @translations.each do |translation| %>
                    <% flag = false %>

                    <% translation.responses.each do |response| %>
                      <% if response.user == current_user %>
                        <% flag = true %>
                      <% end %>
                    <% end %>

                    <% if flag %>
                      <tr>
                        <td><%= translation.user.name %></td>
                        <td><%= translation.subject %></td>
                        <td><%= translation.description %></td>
                        <td><%= I18n.l translation.created_at, format: :short %></td>
                        <td><%= I18n.l translation.updated_at, format: :short %></td>
                        <% if !translation.sourcefile.blank? %>
                          <td><%= link_to "Download", translation.sourcefile.url(:original, false) %></td>
                        <% else %>
                          <td>Nenhum Arquivo Disponível</td>
                        <% end %>
                        <td>
                          <%= link_to 'Visualizar', translation_path(translation) %>
                        </td>
                      </tr>
                    <% end %>

                  <% end %>
                </tbody>
              </table>


            </section>
          </div> <!-- page-content -->
        </div> <!-- row -->
      </div> <!-- container-fluid -->

    </body>
</html>

app/views/responses/new.html.erb
<%= provide(:title, 'Nova Resposta') %>

<head>
    <title><%= full_title(yield(:head_title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'users/application',
        media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'users/application',
        'data-turbolinks-track': 'reload' %>
</head>

<body>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <%= render 'users/layouts/sidebar' %>
        </div> <!-- sidebar -->

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <section id="<%= controller_name %>-<%= action_name %>" >

            <%= render 'devise/shared/flash_messages'%>

            <header class="page-header">
              <h1><%= yield(:title) %></h1>
            </header>

            <%= render 'form' %>

          </section>
        </div> <!-- page-content -->
      </div> <!-- row -->
    </div> <!-- container-fluid -->

app/views/responses/show.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:head_title)) %></title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'users/application',
            media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'users/application',
            'data-turbolinks-track': 'reload' %>
    </head>

    <body>

      <div id="page-header">
           <%= render 'users/layouts/navbar'%>
      </div> <!-- page-header -->


      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
            <%= render 'users/layouts/sidebar' %>
          </div> <!-- sidebar -->

          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <section id="<%= controller_name %>-<%= action_name %>" >

              <%= render 'devise/shared/flash_messages'%>

              <header class="page-header">
                <h1>Detalhes da Tradução</h1>
              </header>
              <p><strong>Usuário: </strong> <%= @translation.user.name %> </p>
              <p><strong>Título: </strong> <%= @translation.subject %> </p>
              <p><strong>Resumo: </strong> <%= @translation.description %> </p>
              <p><strong>Criado em: </strong> <%= I18n.l @translation.created_at %> </p>
              <p><strong>Última atualização:</strong> <%= I18n.l @translation.updated_at %> </p>
              <p><strong>Arquivo da Tradução:</strong> <%= link_to "Download", @translation.sourcefile.url(:original, false) %> </p>

              <header class="page-header">
                <h3>Respostas para esta Tradução</h3>
              </header>

            </section>
          </div> <!-- page-content -->
        </div> <!-- row -->
      </div> <!-- container-fluid -->

    </body>
</html>

app/views/translations/_form.html.erb
<%= simple_form_for @translation do |f| %>
  <div class="form-inputs">
    <%= f.input :subject, autofocus: true %>
    <%= f.input :description %>
    <%= f.input :sourcefile, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>


<% end %>

app/views/translations/edit.html.erb
<%= provide(:title, 'Editar Tradução') %>

<head>
    <title><%= full_title(yield(:head_title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'customers/application',
        media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'customers/application',
        'data-turbolinks-track': 'reload' %>
</head>

<body>



  <div class="center jumbotron"> <h3>Editar Tradução</h3> </dir>
<%= render 'form' %>

app/views/translations/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:head_title)) %></title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'users/application',
            media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'users/application',
            'data-turbolinks-track': 'reload' %>
    </head>

    <body>

      <div id="page-header">
           <%= render 'users/layouts/navbar'%>
      </div> <!-- page-header -->


      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
            <%= render 'users/layouts/sidebar' %>
          </div> <!-- sidebar -->

          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <section id="<%= controller_name %>-<%= action_name %>" >

              <%= render 'devise/shared/flash_messages'%>



              <header class="page-header">
                <h1>Minhas Traduções</h1>
              </header>


              <div class="lead clearfix">
                <%= link_to 'Nova Tradução', new_translation_path,
                  class: 'pull-right btn btn-small btn-success' %>
              </div>
              <table class="table table-hover table-bordered">
                <thead>
                  <tr>
                    <th>Usuário</th>
                    <th>Assunto</th>
                    <th>Descrição</th>
                    <th>Criado em</th>
                    <th>Última atualização</th>
                    <th>Arquivo</th>
                    <th>Opções</th>
                  </tr>
                </thead>
                <tbody>
                  <% @translations.each do |translation| %>


                    <% if translation.user == current_user %>


                      <tr>
                        <td><%= translation.user.name %></td>
                        <td><%= translation.subject %></td>
                        <td><%= translation.description %></td>
                        <td><%= I18n.l translation.created_at, format: :short %></td>
                        <td><%= I18n.l translation.updated_at, format: :short %></td>

                        <% if !translation.sourcefile.blank? %>
                          <td><%= link_to "Download", translation.sourcefile.url(:original, false) %></td>
                        <% else %>
                          <td>Nenhum Arquivo Disponível</td>
                        <% end %>

                        <td>
                          <%= link_to 'Visualizar', translation_path(translation) %> |
                          <%= link_to 'Remover',[translation], method: :delete,  data: { confirm: 'Tem certeza que deseja excluir esta tradução?' } %>
                        </td>
                      </tr>

                    <% end %>

                  <% end %>
                </tbody>
              </table>


            </section>
          </div> <!-- page-content -->
        </div> <!-- row -->
      </div> <!-- container-fluid -->

    </body>
</html>

app/views/translations/new.html.erb
<%= provide(:title, 'Nova Tradução') %>

<head>
    <title><%= full_title(yield(:head_title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'users/application',
        media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'users/application',
        'data-turbolinks-track': 'reload' %>
</head>

<body>

  <div id="page-header">
       <%= render 'users/layouts/navbar'%>
  </div> <!-- page-header -->

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <%= render 'users/layouts/sidebar' %>
        </div> <!-- sidebar -->

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <section id="<%= controller_name %>-<%= action_name %>" >

            <%= render 'devise/shared/flash_messages'%>

            <header class="page-header">
              <h1><%= yield(:title) %></h1>
            </header>

            <%= render 'form' %>

          </section>
        </div> <!-- page-content -->
      </div> <!-- row -->
    </div> <!-- container-fluid -->

app/views/users/dashboard/index.html.erb
<% provide(:title, 'Traduções de Outros Usuários') %>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Usuário</th>
      <th>Assunto</th>
      <th>Descrição</th>
      <th>Criado em</th>
      <th>Última atualização</th>
      <th>Arquivo</th>
      <th>Opções</th>
    </tr>
  </thead>
  <tbody>
    <% @translations.each do |translation| %>

    <% if translation.user != current_user %>

      <tr>
        <td><%= translation.user.name %></td>
        <td><%= translation.subject %></td>
        <td><%= translation.description %></td>
        <td><%= I18n.l translation.created_at, format: :short %></td>
        <td><%= I18n.l translation.updated_at, format: :short %></td>

        <% if !translation.sourcefile.blank? %>
          <td><%= link_to "Download", translation.sourcefile.url(:original, false) %></td>
        <% else %>
          <td>Nenhum Arquivo Disponível</td>
        <% end %>

        <td>
          <%= link_to 'Visualizar', translation_path(translation) %>
        </td>
      </tr>

     <% end %>

    <% end %>
  </tbody>
</table>

app/views/users/layouts/_interpreter_menu.html.erb
<li class="divider"></li>

<li class="header"><span>Traduções</span></li>
<li>
  <%= link_to translations_path, title: "Minhas Traduções" do %>
     Minhas Traduções
  <% end %>
  <%= link_to responses_path, title: "Minhas Respostas" do %>
     Minhas Respostas
  <% end %>
</li>

app/views/users/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
      data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(users_root_path, class: "navbar-brand") do %>
        PHEW! Traduções Colaborativas
      <% end %>
    </div>

    <div id="navbar" class="navbar-collapse collapse">

      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"
            role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to edit_users_user_path(current_user) do %>
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                Meu perfil
              <% end %>
            </li>
            <li role="separator" class="divider"></li>
            <li>
              <%= link_to(destroy_user_session_path, method: :delete) do %>
                <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                Sair
              <% end %>
            </li>
          </ul>
        </li>

      </ul>
    </div>
  </div>
</nav>

app/views/users/layouts/_reviewer_menu.html.erb
<li class="divider"></li>
<li class="header"><span>Revisor</span></li>
<li>
  <%= link_to "#", title: "Revisões" do %>
     Revisões
  <% end %>
</li>
<li>
  <!-- <%= link_to "#", title: "Traduções" do %>
     Traduções
  <% end %> -->
</li>

app/views/users/layouts/_sidebar.html.erb
<div id="sidebar-default-parent">
  <ul id="sidebar-menu">

    <li class="divider"></li>



    <li>
      <%= link_to "Página inicial", users_root_path, title: "Página inicial" %>
    </li>

    <%= render('users/layouts/interpreter_menu') if current_user.has_role? :interpreter %>

    <%= render('users/layouts/reviewer_menu') if current_user.has_role? :reviewer %>

  </ul>
</div>

app/views/users/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:head_title)) %></title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'users/application',
            media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'users/application',
            'data-turbolinks-track': 'reload' %>
    </head>

    <body>

      <div id="page-header">
           <%= render 'users/layouts/navbar'%>
      </div> <!-- page-header -->


      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
            <%= render 'users/layouts/sidebar' %>
          </div> <!-- sidebar -->

          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <section id="<%= controller_name %>-<%= action_name %>" >

              <%= render 'devise/shared/flash_messages'%>

              <header class="page-header">
                <h1><%= yield(:title) %></h1>
              </header>

              <%= yield %>

            </section>
          </div> <!-- page-content -->
        </div> <!-- row -->
      </div> <!-- container-fluid -->

    </body>
</html>

app/views/users/users/_form.html.erb
<%= simple_form_for([:users, @user]) do |f| %>

  <div class="form-inputs">
    <%= f.input :name, autofocus: true %>
    <%= f.input :email %>
    <%= f.input :password, required: true,
        hint: ("#{@minimum_password_length} caracteres no mínimo" if @minimum_password_length) %>
    <%= f.input :password_confirmation, required: true %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/users/_navbar.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
      data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(users_root_path, class: "navbar-brand") do %>
        PHEW
      <% end %>
    </div>

    <div id="navbar" class="navbar-collapse collapse">

      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"
            role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_customer.name %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to edit_customers_customer_path(current_customer) do %>
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                Meu perfil
              <% end %>
            </li>
            <li role="separator" class="divider"></li>
            <li>
              <%= link_to(destroy_customer_session_path, method: :delete) do %>
                <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                Sair
              <% end %>
            </li>
          </ul>
        </li>

      </ul>
    </div>
  </div>
</nav>

app/views/users/users/edit.html.erb
<%= provide(:title, 'Editar Perfil') %>

<%= render 'form' %>

app/views/users/users/index.html.erb
<% provide(:title, 'Usuários') %>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Funções</th>
      <th>Criado em</th>
      <th>Última atualização</th>

    </tr>
  </thead>
  <tbody>
     <% @users.each do |user| %>
       <tr>
         <td><%= link_to user.name, users_user_path(user) %></td>
         <td><%= user.email %></td>
         [<td><%= user.roles.map(&:name).join(', ') %></td>]
         <td><%= I18n.l user.created_at, format: :short %></td>
         <td><%= I18n.l user.updated_at, format: :short %></td>

       </tr>
     <% end %>
  </tbody>
</table>